name: chat
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.1
  shared_preferences: ^2.0.6
  qr_flutter: ^4.0.0
  firebase_auth: ^3.3.3
  firebase_core: ^1.10.5
  fluttertoast: ^8.0.8
  qr_code_scanner: ^0.7.0
  image_picker: 0.8.5
  photo_manager: ^0.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/

